version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: "." 
      args:
        # These set the ARG values in your Dockerfile
        VARIANT: "3.8.13-bullseye"
        USERNAME: "derp"
        USER_UID: 2001
        USER_GID: 2001 
        NODE_VERSION": "none" 

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
